/**
 * Central pt-BR UI strings for the Sales CRM.
 * Code is in English; every user-facing string lives here (ADR-007).
 * No i18n framework, just a single typed object.
 */
export const t = {
  app: {
    name: "CRM de Vendas",
    description: "CRM de vendas: funil, contatos e relatórios",
  },
  common: {
    loading: "Carregando…",
    save: "Salvar",
    saving: "Salvando…",
    cancel: "Cancelar",
    create: "Criar",
    edit: "Editar",
    remove: "Excluir",
    search: "Buscar…",
    close: "Fechar",
    confirm: "Confirmar",
    back: "Voltar",
    all: "Todos",
    yes: "Sim",
    no: "Não",
    // Placeholder for an empty value. En dash, not an em dash: the UI has no
    // em dash anywhere (writing-style gate).
    none: "–",
    actions: "Ações",
    active: "Ativo",
    inactive: "Inativo",
    activate: "Ativar",
    deactivate: "Desativar",
    optional: "opcional",
    copy: "Copiar",
    copied: "Copiado!",
    errorTitle: "Algo deu errado",
    errorRetry: "Tentar novamente",
    emptyDefault: "Nada por aqui ainda.",
    notInformed: "Não informado",
    previous: "Anterior",
    next: "Próxima",
    pageOf: (page: number, total: number) => `Página ${page} de ${total}`,
    requiredField: "Campo obrigatório",
    seeMore: "Ver mais",
  },
  auth: {
    title: "Entrar",
    subtitle: "Acesse com o e-mail e a senha da sua conta",
    email: "E-mail",
    emailPlaceholder: "voce@exemplo.com",
    password: "Senha",
    submit: "Entrar",
    submitting: "Entrando…",
    invalidCredentials: "E-mail ou senha incorretos",
    inactiveUser: "Usuário desativado. Fale com a gestão.",
    genericError: "Não foi possível entrar. Tente novamente.",
    logout: "Sair",
    heroTitleStart: "Do primeiro contato",
    heroTitleAccent: "à matrícula.",
    heroSubtitle:
      "Funil de negociações, fila de leads, tarefas e relatórios da equipe, tudo em um lugar só.",
  },
  nav: {
    myDay: "Meu Dia",
    deals: "Negociações",
    tasks: "Minhas tarefas",
    contacts: "Contatos",
    reports: "Relatórios",
    settings: "Configurações",
    toggleTheme: "Alternar tema",
    openMenu: "Abrir menu",
    myAccount: "Minha conta",
  },
  status: {
    open: "Em andamento",
    won: "Vendida",
    lost: "Perdida",
  },
  qualification: {
    label: "Qualificação",
    levels: {
      1: "Muito frio",
      2: "Frio",
      3: "Morno",
      4: "Quente",
      5: "Muito quente",
    } as Record<number, string>,
  },
  kanban: {
    title: "Negociações",
    newDeal: "Criar negociação",
    deals: (n: number) => (n === 1 ? "1 negociação" : `${n} negociações`),
    coolingBadge: (days: number) => `Esfriando há ${days}d`,
    registerFirstContact: "Registrar 1º contato",
    firstContactAt: (when: string) => `1º contato ${when}`,
    emptyColumn: "Nenhuma negociação nesta etapa",
    emptyBoard: "Nenhuma negociação encontrada com esses filtros.",
    queueTitle: "Fila de novos leads",
    queueSubtitle: "Leads recebidos sem consultor responsável",
    claim: "Assumir",
    claiming: "Assumindo…",
    claimed: "Negociação assumida!",
    filters: {
      pipeline: "Funil",
      owner: "Responsável",
      status: "Status",
      unit: "Unidade",
      cooling: "Só esfriando",
      noNextStep: "Sem próximo passo",
      searchPlaceholder: "Buscar por nome ou curso…",
      clear: "Limpar filtros",
    },
    moveError: "Não foi possível mover a negociação.",
    movedToWonStage:
      "Para concluir a matrícula, use o botão “Marcar vendida” na negociação.",
  },
  cycle: {
    filterLabel: "Ciclo",
    allCycles: "Todos os ciclos",
    activePrefix: "Ciclo ativo",
    countdownDays: (n: number) => (n === 1 ? "Falta 1 dia" : `Faltam ${n} dias`),
    countdownToday: "Último dia do ciclo",
    countdownOver: "Prazo do ciclo encerrado",
    deadlineAt: (date: string) => `Prazo: ${date}`,
  },
  goalsBar: {
    label: "Sua meta do ciclo",
    progress: (won: number, target: number) => `${won} de ${target}`,
  },
  rescue: {
    title: "Resgate",
    tabQueue: "Minha fila",
    subtitle:
      "Leads perdidos em ciclos anteriores com motivo recuperável. Reabrir cria uma negociação nova no ciclo atual; a antiga continua no histórico.",
    reopen: "Reabrir no ciclo atual",
    reopenTitle: "Reabrir no ciclo atual?",
    reopenDescription: (name: string) =>
      `Uma nova negociação será criada para ${name} no ciclo ativo, na primeira etapa, com você como responsável. A negociação perdida permanece no histórico.`,
    reopened: "Negociação reaberta no ciclo atual.",
    openNew: "Abrir a nova negociação",
    lostAt: (when: string) => `Perdida ${when}`,
    fromCycle: (name: string) => `Ciclo de origem: ${name}`,
    age: (age: string) => `há ${age}`,
    empty: "Nenhum lead recuperável no momento.",
    reasonCount: (n: number) => (n === 1 ? "1 lead" : `${n} leads`),
  },
  nextContact: {
    title: "Próximo contato",
    description: "Quando você vai falar com este lead de novo?",
    tomorrow: "Amanhã",
    inDays: (n: number) => `Em ${n} dias`,
    pickDate: "Escolher data",
    skip: "Sem próximo passo",
    suggested: "Sugerido pela cadência",
    saved: "Próximo contato agendado.",
    badgeNone: "Sem próximo passo",
    badgeAt: (date: string) => `Próximo: ${date}`,
    editAria: "Agendar próximo contato",
  },
  quickLog: {
    trigger: "Registrar contato",
    noAnswer: "Sem resposta",
    talkedAdvance: "Conversou, avançar",
    talkedObjection: "Conversou, com objeção",
    visitScheduled: "Agendou visita",
    logged: "Contato registrado.",
    visitTitle: "Agendar visita",
    visitDescription:
      "Informe a data da visita. Ela vira o próximo contato e gera uma tarefa automaticamente.",
    visitDate: "Data da visita",
    visitConfirm: "Agendar visita",
    objectionTitle: "Qual foi a objeção?",
    objectionDescription:
      "Registre a objeção principal desta negociação. Ela alimenta os relatórios de perda.",
    objectionPlaceholder:
      "Ex.: preço, vou pensar, preciso falar com alguém…",
    objectionSave: "Salvar objeção",
    objectionSaved: "Objeção registrada.",
    objectionSelectLabel: "Qual foi a objeção?",
    objectionSelectPlaceholder: "Selecione a objeção",
    objectionOther: "Outra (descrever)",
  },
  objection: {
    cardTitle: "Objeção principal",
    selectPlaceholder: "Selecione a objeção",
    none: "Nenhuma",
    legacy: (text: string) => `Outro: ${text}`,
    rebuttalTitle: "Como contornar",
    respondWhatsApp: "Responder no WhatsApp",
    saved: "Objeção atualizada.",
  },
  checklist: {
    title: "Checklist para concluir",
    subtitle: (stage: string) =>
      `Campos exigidos pela etapa ${stage}. Complete tudo para marcar a venda.`,
    progress: (n: number, m: number) => `${n} de ${m}`,
    goToField: (label: string) => `Ir para o campo ${label}`,
  },
  gate: {
    title: "Faltam campos para mover",
    titleWon: "Faltam campos para concluir",
    description:
      "Esta etapa exige os campos abaixo. Preencha para concluir a ação.",
    saveAndRetry: "Salvar e mover",
    saveAndRetryWon: "Salvar e concluir",
    registerFirstContactNow: "Registrar o 1º contato agora",
    booleanHint: "Precisa estar marcado para avançar.",
  },
  guide: {
    title: "Guia desta etapa",
  },
  whatsapp: {
    withTemplate: "Enviar com mensagem pronta",
    noTemplate: "Sem mensagem",
  },
  myDay: {
    title: "Meu Dia",
    subtitle: "Sua fila de trabalho de hoje, na ordem certa",
    consultantFilter: "Consultor",
    wholeTeam: "Time todo",
    respondNow: "Responder agora",
    respondNowHint: "Leads sem 1º contato. Quanto mais rápido, mais conversão.",
    todayTitle: "Follow-ups de hoje",
    todayHint: "Contatos agendados para hoje e tarefas com vencimento hoje.",
    overdueTitle: "Atrasados",
    overdueHint: "Follow-ups e tarefas que passaram do prazo.",
    coolingTitle: "Esfriando sem próximo passo",
    coolingHint: (days: number) =>
      `Sem interação há mais de ${days} dias e sem contato agendado.`,
    leadAge: (age: string) => `há ${age}`,
    waitingSince: (when: string) => `Lead criado ${when}`,
    scheduledFor: (when: string) => `Agendado: ${when}`,
    taskDue: (date: string) => `Vence em ${date}`,
    taskLabel: "Tarefa",
    allClear: "Tudo em dia",
    allClearHint: "Nenhuma pendência na sua fila. Bora buscar mais leads.",
    sectionEmpty: "Nada por aqui.",
    openDeal: "Abrir negociação",
  },
  dealFields: {
    /** pt-BR labels for GET /deal-fields keys (required-fields catalog). */
    labels: {
      value: "Valor (R$)",
      qualification: "Qualificação",
      unit_id: "Unidade",
      source: "Fonte",
      campaign: "Campanha",
      expected_close_date: "Previsão de fechamento",
      first_whatsapp_contact_at: "1º contato no WhatsApp",
      "contact.phone_whatsapp": "WhatsApp do contato",
      "contact.email": "E-mail do contato",
      "contact.city": "Cidade do contato",
      "enrollment.interest_area": "Área de interesse",
      "enrollment.interest_course": "Curso de interesse",
      "enrollment.entry_method": "Forma de ingresso",
      "enrollment.modality": "Modalidade",
      "enrollment.enrollment_semester": "Semestre de ingresso",
      "enrollment.how_found_us": "Como conheceu",
      "enrollment.budget_range": "Faixa de orçamento",
      "enrollment.needs_scholarship_or_financing":
        "Precisa de bolsa/financiamento?",
      "enrollment.monthly_fee_value": "Valor da mensalidade (R$)",
      "enrollment.scholarship_offered": "Bolsa oferecida",
      "enrollment.negotiated_final_condition": "Condição negociada final",
      "enrollment.payment_method": "Forma de pagamento",
      "enrollment.payment_status": "Status do pagamento",
      "enrollment.payment_date": "Data do pagamento",
      "enrollment.decision_deadline": "Prazo de decisão",
      "enrollment.main_objection": "Objeção principal",
      "enrollment.scheduling_status": "Status do agendamento",
      "enrollment.finished_high_school": "Concluiu o Ensino Médio?",
      "enrollment.cpf": "CPF",
      "enrollment.rg": "RG",
      "enrollment.birth_date": "Data de nascimento",
      "enrollment.address": "Endereço",
      "enrollment.contract_signed": "Contrato assinado?",
      "enrollment.contract_accepted_at": "Data do aceite",
      "enrollment.contract_link": "Link do contrato",
      "enrollment.ra_number": "RA / matrícula gerada",
    } as Record<string, string>,
  },
  deal: {
    detailTitle: "Negociação",
    notFound: "Negociação não encontrada.",
    contact: "Contato",
    phone: "WhatsApp",
    owner: "Responsável",
    noOwner: "Sem responsável",
    unit: "Unidade",
    stage: "Etapa",
    value: "Valor (R$)",
    source: "Fonte",
    campaign: "Campanha",
    expectedCloseDate: "Previsão de fechamento",
    createdAt: "Criada em",
    markWon: "Marcar vendida",
    markLost: "Marcar perdida",
    reopen: "Reabrir negociação",
    openWhatsApp: "Abrir WhatsApp",
    wonDialogTitle: "Marcar como vendida",
    wonDialogDescription:
      "Confirme o valor final da matrícula. A negociação vai para a etapa de matriculados.",
    wonConfirm: "Confirmar venda",
    wonSuccess: "Matrícula registrada! 🎉",
    lostDialogTitle: "Marcar como perdida",
    lostDialogDescription:
      "Informe o motivo da perda. Isso alimenta os relatórios da gestão.",
    lostReason: "Motivo da perda",
    lostReasonPlaceholder: "Selecione o motivo",
    lostNotes: "Detalhes (opcional)",
    lostNotesPlaceholder: "Ex.: objeção principal, o que foi tentado…",
    lostConfirm: "Confirmar perda",
    lostSuccess: "Perda registrada.",
    firstContactDialogTitle: "Registrar 1º contato agora?",
    firstContactDialogDescription:
      "Você está abrindo o WhatsApp deste lead. Quer registrar o primeiro contato? Esse horário é a base da métrica de tempo de resposta e não pode ser alterado depois.",
    firstContactOnlyOpen: "Só abrir o WhatsApp",
    firstContactRegister: "Registrar e abrir",
    firstContactSuccess: "Primeiro contato registrado.",
    firstContactAlready: "O primeiro contato já estava registrado.",
    updateSuccess: "Negociação atualizada.",
    titleLabel: "Título",
    enrollmentTitle: "Dados da matrícula",
    enrollmentSubtitle:
      "Preencha conforme a negociação avança. Tudo é salvo nesta negociação.",
    timelineTitle: "Histórico",
    timelineEmpty: "Nenhuma atividade ainda.",
    addNotePlaceholder: "Escreva uma anotação sobre esta negociação…",
    addNote: "Anotar",
    noteAdded: "Anotação registrada.",
    tasksTitle: "Tarefas",
    tasksEmpty: "Nenhuma tarefa nesta negociação.",
    createTask: "Nova tarefa",
    system: "Sistema",
  },
  activity: {
    note: "Anotação",
    deal_created: "Negociação criada",
    stage_changed: "Mudou de etapa",
    status_changed: "Status alterado",
    first_contact_registered: "1º contato registrado",
    first_contact_corrected: "1º contato corrigido",
    task_created: "Tarefa criada",
    task_completed: "Tarefa concluída",
    owner_changed: "Responsável alterado",
    attempt_no_answer: "Tentativa sem resposta",
    talked_advance: "Conversou, avançando",
    talked_objection: "Conversou, com objeção",
    visit_scheduled: "Visita agendada",
    cycle_changed: "Mudou de ciclo",
    reopened_in_cycle: "Reaberta em novo ciclo",
    unknown: "Atividade",
    nextContactAt: (when: string) => `Próximo contato: ${when}`,
  },
  enrollment: {
    interest: {
      title: "Interesse",
      interest_area: "Área de interesse",
      interest_course: "Curso de interesse",
      entry_method: "Forma de ingresso",
      modality: "Modalidade",
      enrollment_semester: "Semestre de ingresso",
      how_found_us: "Como conheceu",
      entryMethods: {
        vestibular: "Vestibular",
        enem: "ENEM",
        transferencia: "Transferência",
        segunda_graduacao: "Segunda graduação",
        outro: "Outro",
      },
      modalities: {
        presencial: "Presencial",
        semipresencial: "Semipresencial",
        ead: "EAD",
      },
    },
    financial: {
      title: "Financeiro",
      budget_range: "Faixa de orçamento",
      needs_scholarship_or_financing: "Precisa de bolsa/financiamento?",
      monthly_fee_value: "Valor da mensalidade (R$)",
      scholarship_offered: "Bolsa oferecida",
      negotiated_final_condition: "Condição negociada final",
      payment_method: "Forma de pagamento",
      payment_status: "Status do pagamento",
      payment_date: "Data do pagamento",
    },
    qualification: {
      title: "Qualificação e negociação",
      decision_deadline: "Prazo de decisão",
      main_objection: "Objeção principal",
      scheduling_status: "Status do agendamento",
      finished_high_school: "Concluiu o Ensino Médio?",
    },
    documents: {
      title: "Documentos e fechamento",
      cpf: "CPF",
      rg: "RG",
      birth_date: "Data de nascimento",
      address: "Endereço",
      contract_signed: "Contrato assinado?",
      contract_accepted_at: "Data do aceite",
      contract_link: "Link do contrato",
      ra_number: "RA / matrícula gerada",
    },
    saved: "Dados da matrícula salvos.",
  },
  tasks: {
    title: "Minhas tarefas",
    overdue: "Vencidas",
    today: "Hoje",
    upcoming: "Próximas",
    empty: "Nenhuma tarefa pendente. 👏",
    emptyGroup: "Nada aqui.",
    done: "Concluída",
    markDone: "Concluir",
    dueOn: (date: string) => `Vence em ${date}`,
    newTaskTitle: "Nova tarefa",
    taskTitleLabel: "O que precisa ser feito?",
    taskTitlePlaceholder: "Ex.: ligar para confirmar documentos",
    dueDateLabel: "Vencimento",
    created: "Tarefa criada.",
    completed: "Tarefa concluída.",
    openDeal: "Abrir negociação",
  },
  contacts: {
    title: "Contatos",
    newContact: "Novo contato",
    editContact: "Editar contato",
    name: "Nome",
    phone: "WhatsApp",
    phonePlaceholder: "(11) 99999-9999",
    phoneHint: "Com DDD. Ex.: 11 99999-9999",
    email: "E-mail",
    city: "Cidade",
    notes: "Observações",
    empty: "Nenhum contato encontrado.",
    searchPlaceholder: "Buscar por nome ou telefone…",
    created: "Contato criado.",
    updated: "Contato atualizado.",
    duplicatePhone: "Já existe um contato com este WhatsApp.",
    dealsCount: (n: number) => (n === 1 ? "1 negociação" : `${n} negociações`),
  },
  createDeal: {
    title: "Criar negociação",
    description:
      "Informe o lead. Se o WhatsApp já existir nos contatos, a negociação é vinculada à mesma pessoa.",
    contactName: "Nome do lead",
    contactPhone: "WhatsApp",
    course: "Curso de interesse",
    value: "Valor (R$)",
    unit: "Unidade",
    unitPlaceholder: "Selecione a unidade",
    source: "Fonte",
    submit: "Criar negociação",
    success: "Negociação criada.",
  },
  reports: {
    title: "Relatórios",
    subtitle: "Por que não estamos vendendo?",
    filters: {
      period: "Período",
      last7: "Últimos 7 dias",
      last30: "Últimos 30 dias",
      last90: "Últimos 90 dias",
      thisYear: "Este ano",
      unit: "Unidade",
      owner: "Consultor",
    },
    kpi: {
      leads: "Leads no período",
      conversion: "Conversão geral",
      responseTime: "Tempo médio de resposta",
      sales: "Vendas",
      cac: "CAC médio",
      cacEmpty: "sem investimento lançado",
    },
    cac: {
      title: "CAC e custo por lead",
      subtitle:
        "Investimento cruzado com leads e matrículas. Sem lançamento de investimento, o custo aparece como \"sem investimento lançado\", nunca zero.",
      groupBy: {
        source: "Fonte",
        campaign: "Campanha",
        unit: "Unidade",
        month: "Mês",
      },
      spend: "Investimento",
      leads: "Leads",
      enrollments: "Matrículas",
      costPerLead: "Custo por lead",
      costPerEnrollment: "Custo por matrícula",
      leadToEnrollment: "Lead → matrícula",
      noSpend: "sem investimento lançado",
      unattributed: "Sem atribuição",
      empty: "Sem leads nem investimento no período.",
    },
    goals: {
      title: "Metas do ciclo",
      subtitle:
        "Progresso de matrículas contra a meta, por consultor e por unidade",
      consultants: "Ranking de consultores",
      units: "Progresso por unidade",
      who: "Alvo",
      target: "Meta",
      won: "Matrículas",
      pct: "% da meta",
      empty: "Nenhuma meta cadastrada neste ciclo.",
      needCycle: "Selecione um ciclo para ver as metas.",
    },
    conversations: {
      title: "Conversas por consultor",
      subtitle:
        "Tentativas, conversas reais, visitas e objeções contornadas no período",
      consultant: "Consultor",
      attempts: "Tentativas",
      conversations: "Conversas",
      rate: "Contato → conversa",
      visits: "Visitas",
      objections: "Objeções",
      overcome: "Contornadas",
      empty: "Sem registros de conversa no período.",
    },
    funnel: {
      title: "Funil de conversão",
      subtitle: "Quantos leads entram em cada etapa e onde eles morrem",
      entered: "Entraram",
      conversion: "Conversão da etapa anterior",
      /** Diagnostic reading per transition, keyed by target stage position
       * (default 6-stage funnel: each drop points to a distinct problem). */
      diagnostics: {
        2: "Queda aqui: o 1º toque não está sendo feito",
        3: "Queda aqui: problema de contato, o lead não responde",
        4: "Queda aqui: problema de qualificação da conversa",
        5: "Queda aqui: problema de oferta ou preço",
        6: "Queda aqui: fricção de documentos ou pagamento",
      } as Record<number, string>,
    },
    noNextStep: {
      title: "Sem próximo passo por consultor",
      subtitle:
        "Negociações abertas agora sem contato futuro agendado. Foto do presente, não segue o período.",
      consultant: "Consultor",
      queue: "Fila sem dono",
      openDeals: "Abertas",
      withoutNext: "Sem próximo passo",
      pct: "%",
      empty: "Nenhuma negociação aberta no momento.",
    },
    lostReasons: {
      title: "Motivos de perda",
      subtitle: "Ranking de por que os leads não fecham",
      objections: "Objeções mais citadas (texto livre)",
      objectionCatalog: "Objeções do catálogo",
      count: "Perdas",
      empty: "Nenhuma perda registrada no período.",
    },
    responseTime: {
      title: "Tempo de resposta ao lead",
      subtitle: "Quanto tempo cada consultor leva até o 1º contato",
      consultant: "Consultor",
      median: "Mediana",
      average: "Média",
      within24h: "% em 24h",
      neverContacted: "Sem contato",
      empty: "Sem dados de resposta no período.",
    },
    sales: {
      title: "Vendas",
      subtitle: "Matrículas por unidade, consultor e mês",
      month: "Mês",
      unit: "Unidade",
      consultant: "Consultor",
      count: "Matrículas",
      total: "Valor total",
      avgTicket: "Ticket médio",
      empty: "Nenhuma venda no período.",
    },
    cooling: {
      title: "Leads esfriando agora",
      subtitle: "Negociações abertas sem interação além do limite",
      empty: "Nenhum lead esfriando. 👏",
      lastActivity: "Última interação",
      daysIdle: "Dias parado",
    },
  },
  settings: {
    title: "Configurações",
    tabs: {
      users: "Usuários",
      units: "Unidades",
      stages: "Etapas do funil",
      messages: "Mensagens",
      cycles: "Ciclos",
      spend: "Investimento",
      goals: "Metas",
      objections: "Objeções",
      lostReasons: "Motivos de perda",
      leadSources: "Fontes de lead",
      general: "Geral",
    },
    cycles: {
      subtitle:
        "Ciclos de vendas (ex.: semestres de ingresso). Um único ciclo fica ativo por vez; leads novos nascem nele.",
      newCycle: "Novo ciclo",
      name: "Nome",
      namePlaceholder: "Ex.: 2026.2",
      startsOn: "Início",
      deadlineOn: "Prazo final",
      noDeadline: "Sem prazo",
      activeBadge: "Ativo",
      activate: "Ativar",
      activateTitle: (name: string) => `Ativar o ciclo ${name}?`,
      activateWarning:
        "O ciclo atual será desativado. Leads novos, filtros padrão e metas passam a olhar para este ciclo. As negociações continuam nos ciclos onde estão; use \"Rolar leads abertos\" no ciclo antigo se quiser trazê-las.",
      activated: "Ciclo ativado.",
      rollover: "Rolar leads abertos",
      rolloverTitle: (name: string) => `Rolar leads abertos de ${name}`,
      rolloverDescription: (n: number, cycle: string) =>
        n === 1
          ? `1 negociação aberta será movida para o ciclo ativo (${cycle}). Vendidas e perdidas ficam onde estão.`
          : `${n} negociações abertas serão movidas para o ciclo ativo (${cycle}). Vendidas e perdidas ficam onde estão.`,
      rolloverNone: "Nenhuma negociação aberta neste ciclo.",
      rolloverDone: (n: number) =>
        n === 1
          ? "1 negociação movida para o ciclo ativo."
          : `${n} negociações movidas para o ciclo ativo.`,
      created: "Ciclo criado.",
      updated: "Ciclo atualizado.",
      deleted: "Ciclo excluído.",
      deleteHint: "Só ciclos sem negociações podem ser excluídos.",
    },
    spend: {
      subtitle:
        "Lance o investimento de mídia por mês para calcular custo por lead e por matrícula. Sem lançamento, o relatório mostra o custo em branco, nunca zero.",
      month: "Mês",
      source: "Fonte",
      sourcePlaceholder: "Ex.: meta",
      campaign: "Campanha",
      unit: "Unidade",
      amount: "Valor (R$)",
      add: "Lançar investimento",
      created: "Investimento lançado.",
      updated: "Valor atualizado.",
      deleted: "Lançamento excluído.",
      empty: "Nenhum investimento lançado ainda.",
      allUnits: "Todas",
    },
    goals: {
      subtitle:
        "Metas de matrícula por ciclo, por consultor ou por unidade. O progresso aparece no kanban do consultor e nos relatórios.",
      cycle: "Ciclo",
      scope: "Tipo",
      scopeConsultant: "Consultor",
      scopeUnit: "Unidade",
      target: "Meta (matrículas)",
      add: "Criar meta",
      created: "Meta criada.",
      updated: "Meta atualizada.",
      deleted: "Meta excluída.",
      empty: "Nenhuma meta neste ciclo.",
    },
    objections: {
      subtitle:
        "Catálogo de objeções com o contorno sugerido. Aparece no registro de conversa e no detalhe da negociação.",
      name: "Objeção",
      namePlaceholder: "Ex.: Preço",
      rebuttal: "Contorno sugerido",
      rebuttalPlaceholder:
        "Ex.: Pergunte quanto caberia no orçamento hoje e mostre as opções de bolsa.",
      template: "Mensagem vinculada (WhatsApp)",
      noTemplate: "Nenhuma",
      newObjection: "Nova objeção",
      created: "Objeção criada.",
      updated: "Objeção atualizada.",
      deleted: "Objeção excluída.",
      deleteHint: "Se a objeção estiver em uso, desative em vez de excluir.",
      empty: "Nenhuma objeção cadastrada ainda.",
    },
    users: {
      newUser: "Novo consultor",
      name: "Nome",
      email: "E-mail",
      role: "Perfil",
      roleAdmin: "Administrador",
      roleConsultant: "Consultor",
      unit: "Unidade",
      password: "Senha inicial",
      resetPassword: "Redefinir senha",
      newPassword: "Nova senha",
      created: "Usuário criado.",
      updated: "Usuário atualizado.",
      passwordReset: "Senha redefinida.",
      confirmDeactivate:
        "Desativar impede o login, mas mantém o histórico das negociações.",
    },
    units: {
      newUnit: "Nova unidade",
      name: "Nome da unidade",
      updated: "Unidade atualizada.",
      created: "Unidade criada.",
      renameHint: "Clique no nome para renomear.",
    },
    stages: {
      subtitle:
        "Etapas do funil na ordem em que aparecem no kanban. A última etapa marca a matrícula.",
      newStage: "Nova etapa",
      name: "Nome da etapa",
      wonStage: "Etapa de matrícula",
      created: "Etapa criada.",
      updated: "Etapa atualizada.",
      deleted: "Etapa removida.",
      deleteBlocked:
        "Não é possível remover uma etapa que tem negociações. Mova as negociações antes.",
      configure: "Configurar",
      configureTitle: (name: string) => `Configurar etapa: ${name}`,
      requiredFields: "Campos obrigatórios para entrar nesta etapa",
      requiredFieldsHint:
        "Ao mover uma negociação para cá, o sistema exige estes campos preenchidos.",
      requiredCount: (n: number) =>
        n === 1 ? "1 campo obrigatório" : `${n} campos obrigatórios`,
      playbook: "Guia desta etapa (playbook)",
      playbookHint:
        "Aparece para o consultor no detalhe da negociação. Texto simples, com quebras de linha.",
      playbookPlaceholder:
        "Ex.: Descubra objetivo, urgência e orçamento. Pergunte antes de ofertar.",
      configSaved: "Configuração da etapa salva.",
    },
    messages: {
      subtitle:
        "Mensagens prontas para o botão WhatsApp. Use as variáveis para personalizar automaticamente.",
      variablesHint:
        "Variáveis disponíveis: {{first_name}} (primeiro nome do lead), {{course}} (curso de interesse), {{unit}} (unidade), {{consultant}} (consultor).",
      newTemplate: "Nova mensagem",
      name: "Nome",
      namePlaceholder: "Ex.: Primeiro contato",
      body: "Mensagem",
      bodyPlaceholder:
        "Ex.: Olá {{first_name}}! Vi seu interesse em {{course}}. Posso te ajudar?",
      preview: "Prévia com dados de exemplo",
      created: "Mensagem criada.",
      updated: "Mensagem atualizada.",
      deleted: "Mensagem excluída.",
      deleteConfirmHint:
        "Excluir é permanente. Prefira desativar para manter o histórico.",
      empty: "Nenhuma mensagem cadastrada ainda.",
      sampleVars: {
        first_name: "Maria",
        course: "Enfermagem",
        unit: "Unidade Centro",
        consultant: "João",
      },
    },
    lostReasons: {
      newReason: "Novo motivo",
      label: "Motivo",
      created: "Motivo criado.",
      updated: "Motivo atualizado.",
      deactivateHint:
        "Desativar esconde o motivo de novas perdas sem afetar os relatórios antigos.",
      recoverable: "Recuperável",
      recoverableHint:
        "Perdas com motivo recuperável entram na lista de Resgate no ciclo seguinte.",
    },
    leadSources: {
      newSource: "Nova fonte",
      name: "Nome da fonte",
      namePlaceholder: "Ex.: LP Enfermagem (Apps Script)",
      defaultUnit: "Unidade padrão",
      webhookUrl: "URL do webhook",
      webhookHint:
        "Aponte a LP ou o formulário para esta URL. Os leads caem na fila de novos leads.",
      copyUrl: "Copiar URL",
      created: "Fonte criada.",
      updated: "Fonte atualizada.",
      revoked: "Fonte revogada: o webhook parou de aceitar leads.",
      revoke: "Revogar",
      revokedBadge: "Revogada",
      revokeHint:
        "Revogar é permanente: o token para de aceitar leads e não pode ser reativado. Crie uma nova fonte se precisar.",
    },
    general: {
      coolingDays: "Dias para considerar um lead esfriando",
      coolingHint:
        "Sem nenhuma interação por este número de dias, a negociação ganha o alerta “Esfriando”.",
      saved: "Configuração salva.",
    },
  },
  errors: {
    /** Stable API error codes → pt-BR messages (ADR-007). */
    byCode: {
      invalid_credentials: "E-mail ou senha incorretos.",
      user_inactive: "Usuário desativado. Fale com a gestão.",
      unauthorized: "Sessão expirada. Entre novamente.",
      forbidden: "Você não tem permissão para isso.",
      not_found: "Registro não encontrado.",
      deal_not_found: "Negociação não encontrada.",
      contact_not_found: "Contato não encontrado.",
      lost_reason_required: "Informe o motivo da perda.",
      invalid_lost_reason: "Informe um motivo de perda válido.",
      first_contact_already_set: "O 1º contato já estava registrado.",
      duplicate_phone: "Já existe um contato com este WhatsApp.",
      duplicate_contact: "Já existe um contato com este WhatsApp.",
      duplicate_email: "Já existe um usuário com este e-mail.",
      stage_has_deals:
        "A etapa tem negociações. Mova as negociações antes de remover.",
      stage_has_history:
        "A etapa aparece no histórico de negociações e não pode ser removida.",
      sort_order_taken: "Já existe uma etapa nessa posição.",
      won_stage_exists: "O funil já tem uma etapa de matrícula.",
      deal_locked: "Negociação já finalizada. Peça a um administrador para reabrir.",
      deal_already_open: "A negociação já está aberta.",
      deal_already_owned: "Esta negociação já tem um responsável.",
      not_deal_owner: "Só o responsável ou um administrador pode alterar.",
      contact_has_open_deals:
        "O contato ainda tem negociações abertas. Finalize antes de excluir.",
      cannot_create_in_won_stage:
        "Não é possível criar negociações direto na etapa de matrícula.",
      already_revoked: "Esta fonte já foi revogada.",
      rate_limited: "Muitas tentativas. Aguarde um minuto e tente de novo.",
      validation_error: "Confira os campos informados.",
      stage_requirements_missing:
        "Faltam campos obrigatórios para entrar nesta etapa.",
      visit_requires_next_contact_at: "Informe a data da visita.",
      invalid_required_field: "Campo inválido para esta etapa.",
      duplicate_template: "Já existe uma mensagem com este nome.",
      duplicate_cycle: "Já existe um ciclo com este nome.",
      cannot_delete_active_cycle: "Não é possível excluir o ciclo ativo.",
      cycle_has_deals: "O ciclo tem negociações e não pode ser excluído.",
      cannot_rollover_active_cycle: "Este já é o ciclo ativo.",
      no_active_cycle:
        "Nenhum ciclo ativo. Ative um ciclo em Configurações antes.",
      invalid_cycle: "Ciclo inválido.",
      duplicate_spend:
        "Já existe um lançamento para esta combinação de mês, fonte, campanha e unidade.",
      invalid_unit: "Unidade inválida.",
      duplicate_goal: "Já existe uma meta para este alvo neste ciclo.",
      invalid_user: "Consultor inválido.",
      duplicate_objection: "Já existe uma objeção com este nome.",
      invalid_template: "Mensagem vinculada inválida.",
      objection_in_use:
        "A objeção está em uso em negociações. Desative em vez de excluir.",
      invalid_objection: "Objeção inválida ou desativada.",
      objection_requires_talked_objection:
        "A objeção só pode ser registrada no resultado \"Conversou, com objeção\".",
      deal_not_lost:
        "Só negociações perdidas podem ser reabertas em outro ciclo.",
    } as Record<string, string>,
    network: "Sem conexão com o servidor. Verifique sua internet.",
    generic: "Algo deu errado. Tente novamente.",
  },
} as const;

export type Strings = typeof t;
